services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: contacts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d contacts"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis-alpine
    ports:
      - "6379:6379"

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/contacts
      REDIS_URL: redis://redis:6379/0
      MAIL_SERVER: maildev
      MAIL_PORT: 1025
      MAIL_FROM: no-reply@example.com
      MAIL_USE_CREDENTIALS: "false"
      PUBLIC_BASE_URL: http://localhost:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: ["sh", "-c", "poetry run alembic upgrade head && exec poetry run fastapi run"]

volumes:
  db-data:
